version: "3.8"

services:
  app:
    build:
      context: ./
      dockerfile: ./etc/backend/Dockerfile
    env_file:
      - ./etc/backend/env/test.env
      - ./etc/db/env/test.env
    depends_on:
      - db
    volumes:
      - ./src/room_booking:/home/room_booking/room_booking
      - ./src/tests:/home/room_booking/tests
      - ./src/alembic:/home/room_booking/alembic

  db:
    image: postgres:13.3
    volumes:
      - ./etc/db/entypoints:/docker-entrypoint-initdb.d
    env_file: 
      - ./etc/db/env/test.env

  
